### ISSUE TITLE
Cleaning removes some favicons

### ISSUE THREAD

**Issue by rcu641** [bleachbit/bleachbit#1307]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).
Running Bleachbit cleaner removes some favicons in Firefox and Brave browsers. In my example: Amazon favicons. 
![Firefox Bookmarks After Bleachbit run](https://user-images.githubusercontent.com/95238487/143910286-46ac18ec-a32f-45fd-b536-d9bc16543c7a.png)
![Bleachbit Firefox settings](https://user-images.githubusercontent.com/95238487/143910287-eee33cd2-5f73-410a-9d98-9904cea59239.png)
![Firefox Bookmarks Before Bleachbit Run](https://user-images.githubusercontent.com/95238487/143910289-654c11e3-7a20-494e-a2c2-e04921bf6f67.png)
See attached screenshots, before and after and Firefox settings. 

**To Reproduce**

The error happens (sometimes/every time).
Every time

**Expected behavior**
All favicons should be present after cleaning
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]
Windows v10, bleachbit v4.4.2

**Additional context**

**Comment by rados** [comment]
@rcu641 
Thanks for this report. It is in the process of being fixed. It will be helpful if you paste the exact bookmarked urls that should keep their favicons.

**Comment by rcu641** [comment]
I'm sorry, there's a lot of them to paste here, I don't know how many, but it appears to be the same ones in Brave as in Firefox. There appears to be no pattern between the ones that are erased and the ones not. I will say that the favicons in Firefox come back after some time, I don't know why. Here are a few:

https://www.amazon.com/gp/homepage.html/104-5121456-1358306
https://www.walmart.com/
https://login.fidelityrewards.com/onlineCard/login.do
https://www.amazon.com/Amazon-Video/b/?ie=UTF8&node=2858778011&ref_=nav_cs_prime_video
https://support.google.com/googlenest/topic/7029677?hl=en&ref_topic=7029097

**Comment by XhmikosR** [comment]
@rados this looks a lot like https://github.com/bleachbit/bleachbit/issues/1081, although 1081 mentions only Firefox.

Is there any chance the issue could be fixed? I'm still stuck with Bleachbit v4.0.0 due to this issue :/

Thanks!

**Comment by rcu641** [comment]
Greetings! The only other browser I use is Brave, and it doesn't affect it. At least from what I can tell, comparing the Favicons deleted in Firefox with those still present in Brave.
    On Thursday, December 2, 2021, 03:30:03 AM CST, XhmikosR ***@***.***> wrote:  
 
 


@rados this looks a lot like #1081, although 1081 mentions only Firefox.

Is there any chance the issue could be fixed? I'm still stuck with Bleachbit v4.0.0 due to this issue :/

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rados** [comment]
> @rados this looks a lot like #1081, although 1081 mentions only Firefox.
> 
> Is there any chance the issue could be fixed? I'm still stuck with Bleachbit v4.0.0 due to this issue :/
> 
> Thanks!

Yes, it is fixed practically. Now I am polishing the fix, adding a bit more comprehensive unit tests, etc. We had several reports of issues with Firefox favicons during the past year, so I decided this time to put some more efforts in a hope that this will be one really robust fix.

**Comment by lawson85** [comment]
I see missing icons as well but a different kind. See here: 
![image](https://user-images.githubusercontent.com/52282566/152373990-b5d9fbf0-9ddb-4951-b3c3-26155cd1a260.png)
The squares are supposed to be icons that represent the social media. The site is here: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_social_media_buttons

In case this fails here is another example: 
![image](https://user-images.githubusercontent.com/52282566/152374241-c898ef36-ccf2-4041-b15b-7d74de03d23d.png)

https://www.macrodroidforum.com/index.php

**Comment by rados** [comment]
@lawson85, thanks for the report.

You all might want to test the fix that could be downloaded here:

https://ci.appveyor.com/project/az0/bleachbit/builds/42149163/artifacts

**Comment by rcu641** [comment]
This update seems to have fixed my favicon issue, at least with Firefox. I'm still having the favicon removal issue on Brave browser.
Thanks!Randy
    On Thursday, February 3, 2022, 10:18:18 AM CST, Radoslav Stoyanov ***@***.***> wrote:  
 
 


@lawson85, thanks for the report.

You all might want to test the fix that could be downloaded here:

https://ci.appveyor.com/project/az0/bleachbit/builds/42149163/artifacts

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rcu641** [comment]
Apologies, I tried on my laptop, also with brave and the bleachbit update...no issues there. I'm not sure what happened, I'm using brave sync, but not for bookmarks.
    On Thursday, February 3, 2022, 10:18:18 AM CST, Radoslav Stoyanov ***@***.***> wrote:  
 
 


@lawson85, thanks for the report.

You all might want to test the fix that could be downloaded here:

https://ci.appveyor.com/project/az0/bleachbit/builds/42149163/artifacts

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XhmikosR** [comment]
This issue doesn't seem to happen in the latest versions.
