### ISSUE TITLE
BleachBit for *ubuntu 22.04 ? - Cleaner is not usable on this OS because it has no actions

### ISSUE THREAD

**Issue by robots4life** [bleachbit/bleachbit#1571]
**Describe the bug**
Cleaner is not usable on this OS because it has no actions

**To Reproduce**
I am using Kubuntu 22.04.

I downloaded [Ubuntu 21.10 (Impish Indri)](https://www.bleachbit.org/download/file/t?file=bleachbit_4.4.2-0_all_ubuntu2110.deb) from [https://www.bleachbit.org/download/linux](https://www.bleachbit.org/download/linux) and when I start BleacbBit I see this message.

```bash
Cleaner is not usable on this OS because it has no actions: /usr/share/bleachbit/cleaners/teamviewer.xml
automatically hiding cleaner 'adobe_reader'
automatically hiding cleaner 'amsn'
automatically hiding cleaner 'amule'
automatically hiding cleaner 'audacious'
automatically hiding cleaner 'beagle'
automatically hiding cleaner 'brave'
automatically hiding cleaner 'chromium'
automatically hiding cleaner 'd4x'
automatically hiding cleaner 'dnf'
automatically hiding cleaner 'easytag'
automatically hiding cleaner 'elinks'
automatically hiding cleaner 'emesene'
automatically hiding cleaner 'epiphany'
automatically hiding cleaner 'evolution'
automatically hiding cleaner 'exaile'
automatically hiding cleaner 'filezilla'
automatically hiding cleaner 'flash'
automatically hiding cleaner 'gedit'
automatically hiding cleaner 'gftp'
automatically hiding cleaner 'gimp'
automatically hiding cleaner 'gl-117'
automatically hiding cleaner 'gnome'
automatically hiding cleaner 'google_earth'
automatically hiding cleaner 'google_toolbar'
automatically hiding cleaner 'gpodder'
automatically hiding cleaner 'hexchat'
automatically hiding cleaner 'hippo_opensim_viewer'
automatically hiding cleaner 'java'
automatically hiding cleaner 'kde'
automatically hiding cleaner 'konqueror'
automatically hiding cleaner 'liferea'
automatically hiding cleaner 'links2'
automatically hiding cleaner 'midnightcommander'
automatically hiding cleaner 'miro'
automatically hiding cleaner 'nautilus'
automatically hiding cleaner 'nexuiz'
automatically hiding cleaner 'octave'
automatically hiding cleaner 'openofficeorg'
automatically hiding cleaner 'opera'
automatically hiding cleaner 'palemoon'
automatically hiding cleaner 'pidgin'
automatically hiding cleaner 'realplayer'
automatically hiding cleaner 'recoll'
automatically hiding cleaner 'rhythmbox'
automatically hiding cleaner 'screenlets'
automatically hiding cleaner 'seamonkey'
automatically hiding cleaner 'secondlife_viewer'
automatically hiding cleaner 'skype'
automatically hiding cleaner 'slack'
automatically hiding cleaner 'sqlite3'
automatically hiding cleaner 'thunderbird'
automatically hiding cleaner 'transmission'
automatically hiding cleaner 'tremulous'
automatically hiding cleaner 'vim'
automatically hiding cleaner 'vuze'
automatically hiding cleaner 'warzone2100'
automatically hiding cleaner 'waterfox'
automatically hiding cleaner 'wine'
automatically hiding cleaner 'winetricks'
automatically hiding cleaner 'xine'
automatically hiding cleaner 'yum'
automatically hiding cleaner 'zoom'
```

What can I do today to i.e. include `thunderbird` or other software to clean with BleachBit on 22.04 please ?

I also found [https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/bleachbit_4.4.2-1_all.deb.html](https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/bleachbit_4.4.2-1_all.deb.html) but think that is the same version as from the official BleachBit website, correct ?

The error happens (sometimes/every time).
every time

**Expected behavior**
clean the system

**Desktop (please complete the following information):**
System Information

```bash
BleachBit version 4.4.2
Git revision db612a5
GTK version 3.24.33
GTK theme = Breeze
GTK icon theme = breeze-dark
GTK prefer dark theme = True
SQLite version 3.37.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/{$username$}/.config/bleachbit
personal_cleaners_dir = /home/{$username$}/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = plasma
os.getenv('LOGNAME') = {$username$}
os.getenv('{$USERname$}') = {$username$}
os.getenv('SUDO_UID') = None
os.path.expand{$username$}('~') = /home/{$username$}
platform.linux_distribution() = ('Ubuntu', '22.04', 'jammy')
platform.platform = Linux-6.2.0-35-generic-x86_64-with-glibc2.35
platform.version = #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
__file__ = /usr/share/bleachbit/bleachbit/SystemInformation.py
```

Thank you for any help.

:thumbsup: :smile:

**Comment by az0** [comment]
>Cleaner is not usable on this OS because it has no actions: /usr/share/bleachbit/cleaners/teamviewer.xml

This was caused by a bug in that Windows-specific cleaners were included in the Linux package, so I fixed it so these cleaners would not be included in Linux packages.

>What can I do today to i.e. include thunderbird or other software to clean with BleachBit on 22.04 please ?

If it is installed as flatpak, use BleachBit 4.5.1

In the future, one question or issue per GitHub ticket please.

> I also found https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/bleachbit_4.4.2-1_all.deb.html but think that is the same version as from the official BleachBit website, correct ?

About 99.9% the same. It suppresses the notification of new versions, and Ubuntu never upgrades BleachBit within the same distribution. In other words, Ubuntu 22.04 will always have BleachBit 4.4.2, and you will need Ubuntu 23.04 to get BleachBit 4.6.0. 

There may be some other differences too.

In the future, one question or issue per GitHub ticket please.

**Comment by az0** [comment]
Technical note is that the build process had this error

```
[   19s] awk '/os=\"windows/ && /id=\"/ {print FILENAME}' cleaners/*.xml | xargs rm -f
[   19s] awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
```

**Comment by az0** [comment]
>If none of these, what command do you suggest to uninstall BlachBit on Linux please ?

I think you can just install the new version on top of the old, but there's nothing particular bad about any of those three options. I'm not sure it really deletes the configuration, and otherwise, the worst case is you may need to reinstall a dependency.

You can also try `sudo apt remove bleachbit`

>and there I choose the version for 22.04, correct ?
https://download.bleachbit.org/beta/4.5.1/bleachbit_4.5.1-0_all_ubuntu2204.deb

Yes

**Comment by robots4life** [comment]
This is interesting.

As of today I am getting this notification when opening BleachBit.

![Screenshot_20231106_083003](https://github.com/bleachbit/bleachbit/assets/34193243/f6f68f19-cee5-4002-8628-c68ea62813b8)

Is this intended and what version exactly will that be installing ?

**Comment by robots4life** [comment]
@az0 Ok, I removed the old installation and used `bleachbit_4.6.0-0_all_ubuntu2204.deb` to install the current latest version.

[https://www.bleachbit.org/download/file/t?file=bleachbit_4.6.0-0_all_ubuntu2204.deb](https://www.bleachbit.org/download/file/t?file=bleachbit_4.6.0-0_all_ubuntu2204.deb)

```bash
BleachBit version 4.6.0
Git revision ae1605f
GTK version 3.24.33
GTK theme = Breeze
GTK icon theme = breeze-dark
GTK prefer dark theme = True
SQLite version 3.37.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/{$username$}/.config/bleachbit
personal_cleaners_dir = /home/{$username$}/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = plasma
os.getenv('LOGNAME') = {$username$}
os.getenv('{USER}') = {$username$}
os.getenv('SUDO_UID') = None
os.path.expand{$username$}('~') = /home/{$username$}
platform.linux_distribution() = ('Ubuntu', '22.04', 'jammy')
platform.platform = Linux-6.2.0-36-generic-x86_64-with-glibc2.35
platform.version = #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
__file__ = /usr/share/bleachbit/SystemInformation.py
```

However I still get this message when starting BleachBit, and while I do have Thunderbird installed it is not picking it up. 

What could I kindly do to include Thunderbird for cleaning ?

Thank you.

```bash
automatically hiding cleaner 'adobe_reader'
automatically hiding cleaner 'amsn'
automatically hiding cleaner 'amule'
automatically hiding cleaner 'audacious'
automatically hiding cleaner 'beagle'
automatically hiding cleaner 'brave'
automatically hiding cleaner 'chromium'
automatically hiding cleaner 'd4x'
automatically hiding cleaner 'dnf'
automatically hiding cleaner 'easytag'
automatically hiding cleaner 'elinks'
automatically hiding cleaner 'emesene'
automatically hiding cleaner 'epiphany'
automatically hiding cleaner 'evolution'
automatically hiding cleaner 'exaile'
automatically hiding cleaner 'filezilla'
automatically hiding cleaner 'flash'
automatically hiding cleaner 'gedit'
automatically hiding cleaner 'gftp'
automatically hiding cleaner 'gimp'
automatically hiding cleaner 'gl-117'
automatically hiding cleaner 'gnome'
automatically hiding cleaner 'google_earth'
automatically hiding cleaner 'google_toolbar'
automatically hiding cleaner 'gpodder'
automatically hiding cleaner 'hexchat'
automatically hiding cleaner 'hippo_opensim_viewer'
automatically hiding cleaner 'java'
automatically hiding cleaner 'konqueror'
automatically hiding cleaner 'liferea'
automatically hiding cleaner 'links2'
automatically hiding cleaner 'microsoft_edge'
automatically hiding cleaner 'midnightcommander'
automatically hiding cleaner 'miro'
automatically hiding cleaner 'nautilus'
automatically hiding cleaner 'nexuiz'
automatically hiding cleaner 'octave'
automatically hiding cleaner 'openofficeorg'
automatically hiding cleaner 'opera'
automatically hiding cleaner 'palemoon'
automatically hiding cleaner 'pidgin'
automatically hiding cleaner 'realplayer'
automatically hiding cleaner 'recoll'
automatically hiding cleaner 'rhythmbox'
automatically hiding cleaner 'screenlets'
automatically hiding cleaner 'seamonkey'
automatically hiding cleaner 'secondlife_viewer'
automatically hiding cleaner 'skype'
automatically hiding cleaner 'slack'
automatically hiding cleaner 'sqlite3'
automatically hiding cleaner 'thunderbird'
automatically hiding cleaner 'transmission'
automatically hiding cleaner 'tremulous'
automatically hiding cleaner 'vim'
automatically hiding cleaner 'vuze'
automatically hiding cleaner 'warzone2100'
automatically hiding cleaner 'waterfox'
automatically hiding cleaner 'wine'
automatically hiding cleaner 'winetricks'
automatically hiding cleaner 'xine'
automatically hiding cleaner 'yum'
automatically hiding cleaner 'zoom'
```

**Comment by robots4life** [comment]
@az0 The behaviour has not changed since the update, neither Firefox nor Thunderbird are being cleaned. Kindly let me know if there is something else I can do, thank you.

**Comment by robots4life** [comment]
This is not resolved for me, errors keep happening, it seems the issue is closed, there are no replies, in any case, thank you for your help, I will most likely choose to use something else.
