### ISSUE TITLE
Missing Company Name in bleachbit.exe Digital Certificate Causes Issue with Software Updater

### ISSUE THREAD

**Issue by ljmacri** [bleachbit/bleachbit#1629]
I am currently using BleachBit for Windows Portable v4.6.0 on a 64-bit Win 10 Pro v22H2 machine. The digital certificate for bleachbit.exe is **missing a value for the Company field**, as shown in this Sysinternals [Sigcheck](https://learn.microsoft.com/en-us/sysinternals/downloads/sigcheck) v2.90 output:

```
Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\ljmac\Downloads\Test\bleachbit.exe:
        Verified:       Signed
        Signing date:   4:37 PM 05-Nov-2023
        Publisher:      Andrew Ziem
        Company:        n/a
        Description:    BleachBit frees space and maintains privacy by quickly wiping files you don't need and didn't know you had. Supported applications include Edge, Firefox, Google Chrome, VLC, and many others.
        Product:        BleachBit - Free space and maintain privacy
        Prod version:   4.6.0
        File version:   4.6.0
        MachineType:    32-bit
        Binary Version: 4.6.0.0
        Original Name:  bleachbit.exe
        Internal Name:  n/a
        Copyright:      n/a
        Comments:       n/a
        Entropy:        6.192
```
As a result the [UCheck](https://www.adlice.com/ucheck/) v5.x software updater I use to check for available updates for my ~ 80 installed and portable applications is **unable to find the latest available version for BleachBit** (i.e., a UCheck script filters out BleachBit from the scan results as "uninteresting") because this software updater requires a Company name to confirm a match for the program executable. _NOTE: Only one other app I use, [WhyNotWIn11](https://github.com/rcmaehl/WhyNotWin11) Portable v2.5.0.5, has the same problem because of a missing value for "Company"_.

I have reported this issue to the developer of UCheck (see my UCheck bug report at https://github.com/AdliceSoftware/UCheck/issues/28), but the developer has closed that bug report and stated that it is the responsibility of BleachBit to add the missing Company name to the digital certificate of the bleachbit.exe (and possibly bleachbit_console.exe) executable.

![UCheck v5_2_2BleachBit v4_6_0 Part A Latest Version Missing 13 Jan 2023](https://github.com/bleachbit/bleachbit/assets/145856101/fa37c442-01f8-4496-ab49-37e7be49209d)

![UCheck v5_2_2BleachBit v4_6_0 Part B Company Name Missing 13 Jan 2023](https://github.com/bleachbit/bleachbit/assets/145856101/929a2a5f-fe14-48d9-85bb-977b68375112)

**Comment by az0** [comment]
@ljmacri 
Thank you for your patience and for the well-written issue ticket. I pushed a fix, which is building. In 15 minutes or later, check the [CI build site for 4.9.1.2780](https://ci.bleachbit.org/) or newer. Did that fix it?

**Comment by ljmacri** [comment]
I tested today with the portable build of BleachBit v4.9.1.2784-test3 (BleachBit-4.9.1.2784-portable.zip) downloaded from https://ci.bleachbit.org/?prefix=dl/4.9.1.2784-test3/ and the problem is not fixed.

[UCheck](https://www.adlice.com/ucheck/) v6.0.1.0 still ignores this build and the debug log reports:

```
2025/02/26 07:40:42:DEBUG	[UCheck::SearchWellKnownLocation] Found app: E:\Portable\BleachBit 4_9_1_2784 BETA\bleachbit.exe
2025/02/26 07:40:42:DEBUG	[UCheck::ShouldFilter] No program name: E:\Portable\BleachBit 4_9_1_2784 BETA\bleachbit.exe
2025/02/26 07:40:42:DEBUG	[UCheck::SearchWellKnownLocation] App is uninteresting, filtering: E:\Portable\BleachBit 4_9_1_2784 BETA\bleachbit.exe
```
...  and [SigCheck](https://learn.microsoft.com/en-us/sysinternals/downloads/sigcheck
) v2.90 shows **multiple file properties are now missing** (e.g., product name, product version, Company, etc.).

```
Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\ljmac\Downloads\Test\bleachbit.exe:
        Verified:       Unsigned
        Link date:      1:42 PM 22-Jul-2024
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit
        Binary Version: n/a
        Original Name:  n/a
        Internal Name:  n/a
        Copyright:      n/a
        Comments:       n/a
        Entropy:        5.871
```
Please re-open this issue and post back when you have released another unstable (BETA) portable build you would like me to test that includes the **Company Name**, etc. in the file properties.

-----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.5487 * Firefox v135.0.1 * Microsoft Defender v4.18.24090.11-1.1.25010.7 * Malwarebytes Premium v5.2.7.167-1.0.5160 * Macrium Reflect Free v8.0.7783

**Comment by az0** [comment]
[BleachBit 4.9.1 alpha](https://www.bleachbit.org/news/bleachbit-491-alpha) was released with this fix. This is digitally signed, unlike the CI builds. If you have a chance to try it out, leave feedback here about the issue you reported.

```
C:\Users\username\Downloads>sigcheck64.exe BleachBit-4.9.1.2886-setup.exe

Sigcheck v2.90 - File version and signature viewer
Copyright (C) 2004-2022 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\ahz00\Downloads\BleachBit-4.9.1.2886-setup.exe:
        Verified:       Signed
        Signing date:   9:15 PM 3/19/2025
        Publisher:      Open Source Developer, Andrew Ziem
        Company:        BleachBit.org
        Description:    BleachBit Setup
        Product:        BleachBit
        Prod version:   4.9.1.2886.0
        File version:   4.9.1.2886.0
        MachineType:    32-bit
```

**Comment by az0** [comment]
Got it. I found that I need to switch to the new freeze API in py2exe, and then it accepts the version_info data, including company name.  I tested it with a "hello world" program with sigcheck, so next I'll implement this in BleachBit, and I'll let you know when that's ready.

**Comment by ljmacri** [comment]
Hi Andrew:

I can confirm the issue with missing file properties for bleachbit.exe appears to be solved.  I unzippd BleachBit Portable **v4.9.1.2907 BETA** (BleachBit-4.9.1.2907-portable.zip, posted 06-Apr-2025) on my removable USB stick and the bundled bleachbit.exe and bleachbit_console.exe are now both detected by my [UCheck](https://www.adlice.com/ucheck/) software updater as valid executables.

Thanks for the fix.

![Image](https://github.com/user-attachments/assets/66ca6f15-aa3b-4ed9-b9f9-1e138141111b)

-----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.5608 * Firefox v137.0.0 * Microsoft Defender v4.18.25020.1009-1.1.25030.1 * Malwarebytes Premium v5.2.9.176-129.0.5196 * Macrium Reflect Free v8.0.7783 * UCheck Free Portable 64-Bit v6.2.1.0
