### ISSUE TITLE
Text rendering bug

### ISSUE THREAD

**Issue by Coccocoahelper** [bleachbit/bleachbit#1840]
![Image](https://github.com/user-attachments/assets/254d4e77-1021-495e-a639-987b075e6b91)

As you can see, the text is completely incomprehensible. Additionally, I came across a [nearly identical](https://github.com/Col-E/Recaf/issues/634) issue with Recaf years ago (yes, I had a different GitHub account again) — make of that what you will.
This is a regression from the 4.6.2 and priors versions, which did not have this issue (I updated 30 minutes ago).
Sadly, I cannot provide the system information as the troubleshooting documentation says, because I cannot find it at all:

![Image](https://github.com/user-attachments/assets/5ffecfea-218d-4fb6-a1ae-d282eb27f306)

Nonetheless, I am available for further inquiries surrounding this, including testing nightly builds — especially since I use BleachBit to clean up the little amount of storage that I have, on my laptop.

**Comment by Karelak** [comment]
Experiencing kind of same thing with the font rendering as well. I do have cleartype on but even when it was off before the issue was still there:

> BleachBit version = 5.0.0.2936
gi.version = 3.51.0
GTK version = 3.24.43
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version = 3.48.0
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getlocale = ('en_GB', 'ISO8859-1')
platform.uname().version = 10.0.19045
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 3.11.10 (main, Feb 16 2025, 04:46:39) [MSC v.1942 32 bit (Intel)]
IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\SystemInformation.pyc

Issue is both with win 10 theme and not
![Image](https://github.com/user-attachments/assets/d198ac8b-a50c-4ba8-a2f7-d2629d6da9ce)
![Image](https://github.com/user-attachments/assets/3b33b0bb-1b77-4a8d-9ba1-be4080e3d3c4)


My current windows version:
![Image](https://github.com/user-attachments/assets/f4b06c4b-cf8c-40fa-9b93-080ed55e59b3)


This was not in before the major ui redesign happened to fusion style. I think pre 5.0(?) I'm not very up to date with the updates with bleach bit.

Also I'm not exactly sure if this is a bleachbit implementation problem or just how windows struggles with some font rendering when using certain styles. I remember having the same problem when qbitorrent also updated to 5.0 and implemented fusion style instead of the old qt style and for a few days they had the same problem. save with brave for a bit sorry I don't exactly have the sources but I have seen this before when being updated to the new fusion style


Also I've seen before a problem with windows and font rendering can occur when not using 100% display scaling however I am using 100% on 1920x1080


I can provide more stuff if needed sorry for yapping

**Comment by Karelak** [comment]
Weirdly issue is fixed with light mode 

![Image](https://github.com/user-attachments/assets/13dfa341-b1b1-4fb8-a9ef-beaa7e55f8d7)

![Image](https://github.com/user-attachments/assets/58a67d97-abc6-4a30-a4b0-cd034ba6e923)

I'm assuming this might be a problem with just dark mode as it looks like the issue is on both but light mode can just hide it well enough so its readable

**Comment by dftf-stu** [comment]
@Coccocoahelper: a few things I'd suggest you can try and report back if any make a difference:
1. In Menu (the app icon, in the top-left) then Preferences, try changing to the dark-theme, fully-exit the app, then re-launch
2. Again in Preferences, try ticking/checking the "Windows 10 theme" option, then fully-exit the app, then re-launch
3. Once again in Preferences, try changing the language of the app to English, French, Spanish or anything-else, fully-close the app, then re-launch it.  Do they work, and is only the language the app is currently set to (Portuguese, I think?) affected?

And a few things it may help the developer if you can note:
1. Are you using the installer version of BleachBit 5.0, or the portable-version (the ZIP file download)?
2. Which version of Windows are you using (in the Start Menu, type **WINVER** then click on the result)
3. What is the primary-language your Windows is set to display in, and do you have multiple-languages installed?

@Karelak: your issue is just the text being blurry, which is a known-issue currently in the 5.0 release (and is already noted on ticket #1681 ).  You can workaround it by going into Menu > Preferences and then either ticking the "Windows 10 theme" option, or if you wish to use the default dark theme the app comes with, you can edit one of the config-files to change the font the app uses.

**Comment by dftf-stu** [comment]
Hi @Coccocoahelper: it's possible that upgrading from 4.6.2 to 5.0 might cause the issue, as sometimes some files might not get replaced, or an older preferences file might not work.

Go to [https://www.bleachbit.org/download/windows](https://www.bleachbit.org/download/windows) and click on the "BleachBit Portable" link on that page to download the ZIP version.  Extract the ZIP (using Windows' built-in "Extract All..." option, in the right-click menu, or via 7-Zip or WinRAR or similar, if you use those) into a folder on your PC, such as Downloads.  Then go into the new "BleachBit-Portable" folder, then double-click the "bleachbit.exe" file.

Do you still have the issue with the garbled font when using the portable version?

**Comment by Coccocoahelper** [comment]
> Hi [@Coccocoahelper](https://github.com/Coccocoahelper): it's possible that upgrading from 4.6.2 to 5.0 might cause the issue, as sometimes some files might not get replaced, or an older preferences file might not work.
> 
> Go to https://www.bleachbit.org/download/windows and click on the "BleachBit Portable" link on that page to download the ZIP version. Extract the ZIP (using Windows' built-in "Extract All..." option, in the right-click menu, or via 7-Zip or WinRAR or similar, if you use those) into a folder on your PC, such as Downloads. Then go into the new "BleachBit-Portable" folder, then double-click the "bleachbit.exe" file.
> 
> Do you still have the issue with the garbled font when using the portable version?

Yeah, I do. I guess I'll check the config file, and change the settings through there.

EDIT: Still happens with the Windows 10 theme off.

![Image](https://github.com/user-attachments/assets/13ade015-5e21-441c-87c7-0821cd285fb7)

**Comment by dftf-stu** [comment]
Hi @Coccocoahelper : I've just downloaded a fresh-copy of the 5.0 ZIP onto my PC, and changed the language to Portuguese, then tested each of the four theme modes (light and dark, and with "Windows 10 theme" enabled or disabled for both).

I'm not able to replicate the issue:

![Image](https://github.com/user-attachments/assets/c6f3ee27-9ae8-4499-9ad9-855c20cf9063)


So I can only think it may be one of a few things:
- Your PC or laptop uses a high-DPI setting that may be causing the app to break
- Your Windows install might be missing a font the app is trying to use
- It might be a GPU driver issue

Some things you can try:

**High DPI:** in the BleachBit-Portable folder, right-click on "bleachbit.exe" and go to Properties.  Go to the Compatibility tab, then click the "Change high DPI settings".  Try different settings in there, making sure to close BleachBit fully and only re-open it after making a change or you won't see any difference.

**Windows missing a font:** go into the Windows ⚙Settings app, then "Time & Language", then check on both the "Region" and "Language" pages everything is set correctly (for example, nothing is still set as "English").

**GPU issue:** in the Windows ⚙Settings app, go to System then Display.  At the bottom of that page, click "Graphics settings".  On the next page, click "Browse" and then browse to and select the "bleachbit.exe" file, and it will get added to that screen.  Then, if your PC or laptop has multiple GPUs, you can select which one it launches on (e.g. AMD or Nvidia GPU, or built-in Ryzen or Intel graphics on the CPU).  Again, after making the change, fully-close the app and re-launch it.  If it works set to one option, the other likely has a driver-issue.  Either update the driver, or just leave the app set to launch on the GPU it works on.

**Comment by Coccocoahelper** [comment]
> Hi [@Coccocoahelper](https://github.com/Coccocoahelper) : I've just downloaded a fresh-copy of the 5.0 ZIP onto my PC, and changed the language to Portuguese, then tested each of the four theme modes (light and dark, and with "Windows 10 theme" enabled or disabled for both).
> 
> I'm not able to replicate the issue:
> 
> ![Image](https://github.com/user-attachments/assets/c6f3ee27-9ae8-4499-9ad9-855c20cf9063)
> 
> So I can only think it may be one of a few things:
> 
> * Your PC or laptop uses a high-DPI setting that may be causing the app to break
> * Your Windows install might be missing a font the app is trying to use
> * It might be a GPU driver issue
> 
> Some things you can try:
> 
> **High DPI:** in the BleachBit-Portable folder, right-click on "bleachbit.exe" and go to Properties. Go to the Compatibility tab, then click the "Change high DPI settings". Try different settings in there, making sure to close BleachBit fully and only re-open it after making a change or you won't see any difference.
> 
> **Windows missing a font:** go into the Windows ⚙Settings app, then "Time & Language", then check on both the "Region" and "Language" pages everything is set correctly (for example, nothing is still set as "English").
> 
> **GPU issue:** in the Windows ⚙Settings app, go to System then Display. At the bottom of that page, click "Graphics settings". On the next page, click "Browse" and then browse to and select the "bleachbit.exe" file, and it will get added to that screen. Then, if your PC or laptop has multiple GPUs, you can select which one it launches on (e.g. AMD or Nvidia GPU, or built-in Ryzen or Intel graphics on the CPU). Again, after making the change, fully-close the app and re-launch it. If it works set to one option, the other likely has a driver-issue. Either update the driver, or just leave the app set to launch on the GPU it works on.

I tried all of those things, and none worked. However, bold fonts were never garbled in the first place. Any ideas?

**Comment by dftf-stu** [comment]
@Coccocoahelper : I can't really think of much else, no. 

My PC also has Windows 10 64-bit 22H2 19045.5854 (so same as yours), just with English International as the display-language.  When I downloaded the ZIP, and set BleachBit to Portuguese, I couldn't replicate the issue, so it may not be with the app itself.

There must be an app on your PC, or a settings-difference, causing the issue.  You could perhaps check the following:
- Do you use any accessibility apps, such as a screen-reader?
- Do you have Windows set to any sort of high-contrast theme?
- Are you using any third-party theming app or UI modifier (e.g. OpenShell, ClassicShell or similar)?

If no, try a repair of your Windows 10 system (it's safe, and you won't lose any files or apps):
- In the Start Menu, search for **Command Prompt**, right-click the result and choose "Run as Administrator"
- In the window that appears, type: `DISM /Online /Cleanup-Image /RestoreHealth` then press Enter
- Once that command finishes, type: `SFC /SCANNOW` and press ENTER
- Restart your PC once that command has finished, then run BleachBit again after

If there is still an issue, try [adding a new user account](https://www.itechguides.com/add-local-user-windows-10/#Option_2_Create_a_Local_User_From_Windows_Settings) to your PC, then test the app under that account.  If it works, you must have an app running when logged in as your usual one causing the issue.  If BleachBit is still broken even under a new account, I'll have to let the developer of the app discuss it further with you, but it may not be something they can solve.

**Comment by dftf-stu** [comment]
@Coccocoahelper : one other thing -- did you test if this still happens when BleachBit is set to a different language?

If not, go into the Preferences screen in BleachBit, then use the dropdown to change to English US or English UK:
![Image](https://github.com/user-attachments/assets/4ed396e3-0ec0-44e8-a988-103c5206baec)

Fully-close the app after changing it, then wait 5-10 seconds, and start BleachBit up again.

If the issue does not occur when set to English, you could leave it set like that as a workaround, given you can speak it.

**Comment by Coccocoahelper** [comment]
> [@Coccocoahelper](https://github.com/Coccocoahelper) : one other thing — did you test if this still happens when BleachBit is set to a different language?
> 
> If not, go into the Preferences screen in BleachBit, then use the dropdown to change to English US or English UK: ![Image](https://github.com/user-attachments/assets/4ed396e3-0ec0-44e8-a988-103c5206baec)
> 
> Fully-close the app after changing it, then wait 5-10 seconds, and start BleachBit up again.
> 
> If the issue does not occur when set to English, you could leave it set like that as a workaround, given you can speak it.

Since I could not change it through the GUI, I edited the `bleachbit.ini` file manually. Still happens, just with a different garble (it appears to be deterministic, so a workaround is theoretically possible):

![Image](https://github.com/user-attachments/assets/a68adfde-48a7-4c13-b997-2911e694445f)

**Comment by dftf-stu** [comment]
@Coccocoahelper : I might have to let the developer, @az0 , pick this one up as I honestly can't think of anything else it could be

All I could suggest further is to see if this issue occurs on a different PC or laptop which also has Windows 10 22H2 installed and where Portuguese is set as the Windows display-language.  You can download the ZIP version to test, as once you've tested, simply delete the ZIP and the folder off that PC and no trace is left behind.  Also, don't worry if you don't have admin rights on whichever other PC you could test on -- just click "No" when it asks for an admin password, and the app will still run.

**Comment by az0** [comment]
@tordenflesk 
Did you update from BleachBit version 4? If so, please check version 5.0.0 was not installed over the the old 4. 

Which is your [Windows display language](https://support.microsoft.com/en-us/windows/manage-the-language-and-keyboard-input-layout-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2)?

@Coccocoahelper @tordenflesk 

Let's check a few things, please.

1. Open Control Panel:  Clock and Region: **Region**.
2. Click the **Administrative** tab.
3. Click  the **Change system locale** button.
4. Please let me know the settings for **Current system locale** and **Use Unicode**

![Image](https://github.com/user-attachments/assets/7555404e-a262-43be-8fe7-ddd1fd7fb2dd)

Next, let's check console system information

1. Open  Command Prompt or Terminal.
2. Type `"c:\program files (x86\bleachbit\bleachbit_console.exe" --sysinfo` and hit ENTER. (The directory may differ on your system.)
3. Please copy the lines with the following info and paste it here

```
BleachBit version = 5.0.0
gi.version = 3.50.0
GTK version = 3.24.49
GTK theme = Yaru-dark
GTK icon theme = Yaru-dark
GTK prefer dark theme = False
SQLite version = 3.46.1
locale.getlocale = ('en_US', 'UTF-8')
```

Then, try to disable the translations.

1. Open Windows File Explorer.
2. Navigate to the folder `C:\Program Files (x86)\BleachBit\share`.
3. Rename the folder `locale` to another name like `disabled`.
4. Restart BleachBit.

In case the configuration is corrupt

1. Open Windows File Explorer.
2. In the address bar type `%appdata\bleachbit%` and hit ENTER.
3. Rename `bleachbit.ini` to something like `bleachbit_old.ini`.
4. Restart BleachBit.

fontconfig  is not likely, but if you don't mind trying

1. Open Windows File Explorer.
2. In the address bar type `%localappdata%` and hit ENTER.
3. Do you have a folder named `fontconfig`? Rename or delete it.
4. Restart BleachBit.

**Comment by tordenflesk** [comment]
1: Norsk Bokmål (Norge)

2: UTF-8 Unchecked

3: BleachBit version = 5.0.0.2936
gi.version = 3.51.0
GTK version = 3.24.43
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version = 3.48.0
local_cleaners_dir = C:\Users\margrethe\scoop\apps\bleachbit\current\cleaners
locale_dir = C:\Users\margrethe\scoop\apps\bleachbit\current\share\locale\
options_dir = C:\Users\margrethe\scoop\apps\bleachbit\current
personal_cleaners_dir = C:\Users\margrethe\scoop\apps\bleachbit\current\cleaners
system_cleaners_dir = C:\Users\margrethe\scoop\apps\bleachbit\current\share\cleaners\
locale.getlocale = ('nb_NO', 'UTF-8')
os.getenv(APPDATA) = C:\Users\margrethe\AppData\Roaming
os.getenv(cd) = C:\Users\margrethe\Desktop
os.getenv(LocalAppData) = C:\Users\margrethe\AppData\Local
os.getenv(LocalAppDataLow) = C:\Users\margrethe\AppData\LocalLow
os.getenv(Music) = C:\Users\margrethe\Music
os.getenv(USERPROFILE) = C:\Users\margrethe
os.getenv(ProgramFiles) = C:\Program Files (x86)
os.getenv(ProgramW6432) = C:\Program Files
os.getenv(TMP) = C:\Users\MARGRE~1\AppData\Local\Temp
os.path.expanduser(~") = C:\Users\margrethe
platform.uname().version = 10.0.19045
sys.argv = ['C:\\Users\\margrethe\\scoop\\apps\\bleachbit\\current\\bleachbit_console.exe', '--sysinfo']
sys.executable = C:\Users\margrethe\scoop\apps\bleachbit\current\bleachbit_console.exe
sys.version = 3.11.10 (main, Feb 16 2025, 04:46:39) [MSC v.1942 32 bit (Intel)]
IsUserAnAdmin() = True
__file__ = C:\Users\margrethe\scoop\apps\bleachbit\current\library.zip\bleachbit\SystemInformation.pyc

4: None of those worked.

**Comment by tordenflesk** [comment]
Downgrading to 4.6.2 "fixed" it for me.

**Comment by az0** [comment]
**Please try the special build [5.0.0.2972-badtext](https://ci.bleachbit.org/?prefix=dl/5.0.0.2972-badtext/)**. It may not fix the issue, but it will help with troubleshooting.  When it starts, this is what it looks like for me. 

![Image](https://github.com/user-attachments/assets/34e39c21-7eb5-4180-a952-51886b7573c1)

In the log area, it shows a variety of text patterns using different styles.  From what I've seen so far, bold and italics are unaffected, while the regular font, strike through, underline, and larger font are affected.  An insight from [another issue ticket](https://github.com/bleachbit/bleachbit/issues/1848#issuecomment-2928895091) is that the broken font is a character shift: it's reproducible by taking regular text, converting each character to an ordinal, subtracting one (like in the ASCII table), and then converting it back to a character.

In this build in the header bar (top right) are new, temporary buttons to toggle the theme, change the font, and show system information.  The font button cycles through eight fonts. From what I've seen so far in another issue ticket, Segoe UI is the only affected font, yet it's also the default. **On your system, is Segoe UI the only affected font?**

The last button (system information) includes new information related to this issue. If possible, please **copy this info as text to the clipboard and paste it here as text**. You may omit anything above `locale_cleaners_dir`. (I don't need any paths.) I included a screenshot to show the position of the button to copy info to the clipboard.

![Image](https://github.com/user-attachments/assets/19b139f1-27c3-44ff-8afb-40927c79a14f)

Here is my system information

```
BleachBit version = 5.0.0
gi.version = 3.51.0
GTK version = 3.24.43
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
GTK font name = Segoe UI 9
SQLite version = 3.48.0
locale.getlocale = ('en_US', 'ISO8859-1')
GTK_CONFIG_HOME = found
GTK_CSS = not found
GTK_SETTINGS_INI = not found
Windows Registry CodePage ACP = 1252
Windows Registry CodePage OEMCP = 437
Windows Registry CodePage MACCP = 10000
Windows API GetACP = 1252
Windows API GetOEMCP = 437
Windows API MaxCharSize = 1
Windows LCID = 1033
Windows GetUserDefaultUILanguage = 1033
Windows GetUserPreferredUILanguages = en-US
Windows GetThreadPreferredUILanguages = en-US, en
Windows locale = en_US
Display Count = 1
Display 0 Name = \\.\DISPLAY1
Display 0 String = VirtualBox Graphics Adapter (WDDM)
Display 0 Resolution = 0x0
Display 0 DPI = 96x96
Display 0 Scale = 100% x 100%
Display 1 Scale (legacy) = 100% x 100%
segoeui.ttf size = 975,088 bytes
tahoma.ttf size = 951,868 bytes
Font Smoothing Enabled = True
Font Smoothing Type = ClearType
Font registry: Segoe UI (TrueType) = segoeui.ttf
Font registry: Segoe UI Bold (TrueType) = segoeuib.ttf
Font registry: Segoe UI Bold Italic (TrueType) = segoeuiz.ttf
Font registry: Segoe UI Italic (TrueType) = segoeuii.ttf
Font registry: Segoe UI Light (TrueType) = segoeuil.ttf
Font registry: Segoe UI Semibold (TrueType) = seguisb.ttf
Font registry: Segoe UI Symbol (TrueType) = seguisym.ttf
Font registry: Tahoma (TrueType) = tahoma.ttf
Font registry: Tahoma Bold (TrueType) = tahomabd.ttf
Font Substitute: Segoe UI = not found
Font Substitute: Tahoma = not found
```

By the way, there are new shortcuts that may not help, but FYI:
*  F11 toggles full screen
* CTRL+SHIFT with PLUS or MINUS changes the font size

BleachBit uses GTK for its graphical interface. **Do you know of any other GTK applications** you have installed such as GIMP, Inkscape, AbiWord, Gnumeric, Gnucash, Pidgin, Deluge, or HexChat? Or did you maybe have them installed earlier and then uninstalled them?

> Downgrading to 4.6.2 "fixed" it for me.

Yes. Besides using this special build to change the font, another option is to [downgrade to 4.6.2](https://www.bleachbit.org/download/old). Old versions are still available.

**Comment by tordenflesk** [comment]
Yes, only Segoe UI's affected:
```
BleachBit version = 5.0.0.2972
gi.version = 3.51.0
GTK version = 3.24.43
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
GTK font name = Segoe UI 9
SQLite version = 3.48.0
locale.getlocale = ('nb_NO', 'ISO8859-1')
GTK_CONFIG_HOME = found
GTK_CSS = not found
GTK_SETTINGS_INI = not found
Windows Registry CodePage ACP = 65001
Windows Registry CodePage OEMCP = 65001
Windows Registry CodePage MACCP = 65001
Windows API GetACP = 65001
Windows API GetOEMCP = 65001
Windows API MaxCharSize = 4
Windows LCID = 1044
Windows GetUserDefaultUILanguage = 1044
Windows GetUserPreferredUILanguages = nb-NO, en-US
Windows GetThreadPreferredUILanguages = nb-NO, nb, no, en-US
Windows locale = nb_NO
Display Count = 1
Display 0 Name = \\.\DISPLAY49
Display 0 String = Microsoft Remote Display Adapter
Display 0 Resolution = 0x0
Display 0 DPI = 96x96
Display 0 Scale = 100% x 100%
Display 1 Scale (legacy) = 100% x 100%
Display 1 Name = \\.\DISPLAY50
Display 1 String = Microsoft Remote Display Adapter
Display 1 Resolution = Unknown
Display 1 DPI = 96x96
Display 1 Scale = 100% x 100%
Display 2 Scale (legacy) = 100% x 100%
Display 2 Name = \\.\DISPLAY51
Display 2 String = Microsoft Remote Display Adapter
Display 2 Resolution = Unknown
Display 2 DPI = 96x96
Display 2 Scale = 100% x 100%
Display 3 Scale (legacy) = 100% x 100%
Display 3 Name = \\.\DISPLAY52
Display 3 String = Microsoft Remote Display Adapter
Display 3 Resolution = Unknown
Display 3 DPI = 96x96
Display 3 Scale = 100% x 100%
Display 4 Scale (legacy) = 100% x 100%
Display 4 Name = \\.\DISPLAY53
Display 4 String = Microsoft Remote Display Adapter
Display 4 Resolution = Unknown
Display 4 DPI = 96x96
Display 4 Scale = 100% x 100%
Display 5 Scale (legacy) = 100% x 100%
Display 5 Name = \\.\DISPLAY54
Display 5 String = Microsoft Remote Display Adapter
Display 5 Resolution = Unknown
Display 5 DPI = 96x96
Display 5 Scale = 100% x 100%
Display 6 Scale (legacy) = 100% x 100%
Display 6 Name = \\.\DISPLAY55
Display 6 String = Microsoft Remote Display Adapter
Display 6 Resolution = Unknown
Display 6 DPI = 96x96
Display 6 Scale = 100% x 100%
Display 7 Scale (legacy) = 100% x 100%
Display 7 Name = \\.\DISPLAY56
Display 7 String = Microsoft Remote Display Adapter
Display 7 Resolution = Unknown
Display 7 DPI = 96x96
Display 7 Scale = 100% x 100%
Display 8 Scale (legacy) = 100% x 100%
Display 8 Name = \\.\DISPLAY57
Display 8 String = Microsoft Remote Display Adapter
Display 8 Resolution = Unknown
Display 8 DPI = 96x96
Display 8 Scale = 100% x 100%
Display 9 Scale (legacy) = 100% x 100%
Display 9 Name = \\.\DISPLAY58
Display 9 String = Microsoft Remote Display Adapter
Display 9 Resolution = Unknown
Display 9 DPI = 96x96
Display 9 Scale = 100% x 100%
Display 10 Scale (legacy) = 100% x 100%
Display 10 Name = \\.\DISPLAY59
Display 10 String = Microsoft Remote Display Adapter
Display 10 Resolution = Unknown
Display 10 DPI = 96x96
Display 10 Scale = 100% x 100%
Display 11 Scale (legacy) = 100% x 100%
Display 11 Name = \\.\DISPLAY60
Display 11 String = Microsoft Remote Display Adapter
Display 11 Resolution = Unknown
Display 11 DPI = 96x96
Display 11 Scale = 100% x 100%
Display 12 Scale (legacy) = 100% x 100%
Display 12 Name = \\.\DISPLAY61
Display 12 String = Microsoft Remote Display Adapter
Display 12 Resolution = Unknown
Display 12 DPI = 96x96
Display 12 Scale = 100% x 100%
Display 13 Scale (legacy) = 100% x 100%
Display 13 Name = \\.\DISPLAY62
Display 13 String = Microsoft Remote Display Adapter
Display 13 Resolution = Unknown
Display 13 DPI = 96x96
Display 13 Scale = 100% x 100%
Display 14 Scale (legacy) = 100% x 100%
Display 14 Name = \\.\DISPLAY63
Display 14 String = Microsoft Remote Display Adapter
Display 14 Resolution = Unknown
Display 14 DPI = 96x96
Display 14 Scale = 100% x 100%
Display 15 Scale (legacy) = 100% x 100%
Display 15 Name = \\.\DISPLAY64
Display 15 String = Microsoft Remote Display Adapter
Display 15 Resolution = Unknown
Display 15 DPI = 96x96
Display 15 Scale = 100% x 100%
Display 16 Scale (legacy) = 100% x 100%
segoeui.ttf size = 955,804 bytes
tahoma.ttf size = 939,280 bytes
Font Smoothing Enabled = True
Font Smoothing Type = ClearType
Font registry: Segoe UI (TrueType) = 
Font registry: Segoe UI Bold (TrueType) = 
Font registry: Segoe UI Bold Italic (TrueType) = 
Font registry: Segoe UI Italic (TrueType) = 
Font registry: Segoe UI Light (TrueType) = 
Font registry: Segoe UI Semibold (TrueType) = 
Font registry: Segoe UI Symbol (TrueType) = 
Font registry: Tahoma (TrueType) = tahoma.ttf
Font registry: Tahoma Bold (TrueType) = tahomabd.ttf
Font Substitute: Segoe UI = Fira Code
Font Substitute: Tahoma = not found
```

**Comment by dftf-stu** [comment]
Not sure if it will help, but I've just tested this in a Windows 10 x64 22H2 virtual-machine and couldn't replicate it.

The VM was installed as English UK (from the "English International" ISO) and I ran BleachBit first without making any changes:
![Image](https://github.com/user-attachments/assets/2eb5e2ba-2fd1-4725-8817-b73d1520ceae)

I then changed BleachBit's language to Portuguese, closed the app, and re-launched it:
![Image](https://github.com/user-attachments/assets/308eb2a7-98cf-46c5-9778-c03e1f1673ae)

I then went into the Windows ⚙Settings app > "Time & Language" > Language > "Add a Language" and then added Portuguese, asking Windows to set it as the display-language, and rebooted after.

I re-extracted BleachBit from the ZIP (to ensure all settings start afresh) and it rendered fine:
![Image](https://github.com/user-attachments/assets/af04baa6-abaa-47dd-b996-acc0e4da8a1c)


The VM screen is running at 100% DPI, if that helps.

@az0: any log that might be useful to compare, or setting I could change to see if it breaks?

**Comment by az0** [comment]
@tordenflesk 

> Yes, only Segoe UI's affected

For this bug, I'm zeroing on Segoe UI, like font substitution.

> GTK_CONFIG_HOME = found
> GTK_CSS = not found
> GTK_SETTINGS_INI = not found

I'm curious if there are any files in `%LOCALAPPDATA%\gtk-3.0` related to fonts settings or font substitution? It found the directory but not `gtk.css` or `settings.ini`.

> Windows GetUserPreferredUILanguages = nb-NO, en-US
> Windows GetThreadPreferredUILanguages = nb-NO, nb, no, en-US
> Windows locale = nb_NO

So far I haven't found someone with an English display language to have this problem.

> Display 14 Scale = 100% x 100%
> Display 15 Scale (legacy) = 100% x 100%
> Display 15 Name = \\.\DISPLAY64
> Display 15 String = Microsoft Remote Display Adapter
> Display 15 Resolution = Unknown
> Display 15 DPI = 96x96
> Display 15 Scale = 100% x 100%
> Display 16 Scale (legacy) = 100% x 100%

Wow, that's many displays!

> Font Substitute: Segoe UI = Fira Code

Your system substitutes Segoe UI with Fira Code. **Did you install Fira Code** through Chocolatey or scoop? Or do you use an IDE such as Visual Studio Code, JetBrains IDEs, Atom, Sublime Text?

@dftf-stu 

I tried something similar to set up another language (Spanish) in a virtual machine, but I couldn't replicate it.


Thank you both for testing and your feedback.

**Comment by tordenflesk** [comment]
gtk3.0 is just an empty folder
No idea why so many displays are detected, probably related to remote desktop.

I have set the system font to Fira Code using Winaero Tweaker, changing to the Nerd Font variant of Fira Code (while causing other issues), and now back to Fira Code again. Seems to have just started working again...

**Comment by az0** [comment]
> I have set the system font to Fira Code using Winaero Tweaker, changing to the Nerd Font variant of Fira Code (while causing other issues), and now back to Fira Code again. Seems to have just started working again...

@tordenflesk 
Thank you. Now I found one way to reproduce this, which was helpful for testing.  Specifically, I ran `choco install firacodeng` to get FiraCode NF version 6.2.0. Then I used Winaero Tweaker to set it as the system font, which substitutes it for Segoe UI. 

Here's what I found in testing.

Setting the Windows system font to Times New Roman doesn't trigger the problem in BleachBit, so it's not font substitution in general. Setting BleachBit to FiraCode NF doesn't trigger the bug, so it's the specific substitution.  The issue may happen with substituting some other fonts, but it's not all fonts.

The bug is related to the font stack involving GTK, pango (used for displaying text), and Windows, but it's hard to pinpoint and fix.  It happens when the stack is compiled with vcpkg, but not with msys2---though I couldn't compare the same versions of all the packages in the stack.

The bug seems _not_ related to:

* Windows Region Settings: Current system locale/Use Unicode UTF-8 for worldwide language support
* display language in BleachBit
* Windows vs Adwaita theme in BleachBit
* dark/light theme in BleachBit
* gtk.css (can be used to pick a different font, which helps)
* deleting the `%localappdata%\fontconfig` directory

@Coccocoahelper

**Have you done any of these?**

* Used Winaero Tweaker
* Changed your Windows system font another way like editing the registry
* Installed the font Fira Code NF
* Set up any font substitutions, specially for Segoe UI (default system font on Windows)

Please try the new build [5.0.0.2974-badtext](https://ci.bleachbit.org/?prefix=dl/5.0.0.2974-badtext/). The bug  is not fixed, by default, it will not use Segoe UI. You can pick other fonts using the headerbar (main window) or in the preferences dialog.

On the toolbar is a button to show system information, and today I enhanced it to record more info that may help. **Please copy that information to the clipboard, and paste it here.** You may delete the line with `local_options_dir` and all lines below.

**Comment by tordenflesk** [comment]
```
BleachBit version = 5.0.0.2974
gi.version = 3.51.0
GTK version = 3.24.43
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
GTK font name = DejaVu Sans 10
Cairo version = 1.18.4
Pango version = 1.56.1
HarfBuzz version = 10.2.0
SQLite version = 3.48.0
locale.getlocale = ('nb_NO', 'ISO8859-1')
GTK_CONFIG_HOME = found
GTK_CSS = not found
GTK_SETTINGS_INI = not found
Windows fontconfig directory = found
Windows fontconfig cache\98094c095b294bb672d43e149439dbe2-le32d8.cache-6 = 80 bytes
Windows fontconfig cache\CACHEDIR.TAG = 204 bytes
Windows fontconfig cache\ef9c9ad8cc5857eb63cb3660bc8bd202-le32d8.cache-6 = 1,694,320 bytes
Windows Registry CodePage ACP = 65001
Windows Registry CodePage OEMCP = 65001
Windows Registry CodePage MACCP = 65001
Windows API GetACP = 65001
Windows API GetOEMCP = 65001
Windows API MaxCharSize = 4
Windows LCID = 1044
Windows GetUserDefaultUILanguage = 1044
Windows GetUserPreferredUILanguages = nb-NO, en-US
Windows GetThreadPreferredUILanguages = nb-NO, nb, no, en-US
Windows locale = nb_NO
Display Count = 1
Display 0 Name = \\.\DISPLAY65
Display 0 String = Microsoft Remote Display Adapter
Display 0 Resolution = 0x0
Display 0 DPI = 96x96
Display 0 Scale = 100% x 100%
Display 1 Scale (legacy) = 100% x 100%
Display 1 Name = \\.\DISPLAY66
Display 1 String = Microsoft Remote Display Adapter
Display 1 Resolution = Unknown
Display 1 DPI = 96x96
Display 1 Scale = 100% x 100%
Display 2 Scale (legacy) = 100% x 100%
Display 2 Name = \\.\DISPLAY67
Display 2 String = Microsoft Remote Display Adapter
Display 2 Resolution = Unknown
Display 2 DPI = 96x96
Display 2 Scale = 100% x 100%
Display 3 Scale (legacy) = 100% x 100%
Display 3 Name = \\.\DISPLAY68
Display 3 String = Microsoft Remote Display Adapter
Display 3 Resolution = Unknown
Display 3 DPI = 96x96
Display 3 Scale = 100% x 100%
Display 4 Scale (legacy) = 100% x 100%
Display 4 Name = \\.\DISPLAY69
Display 4 String = Microsoft Remote Display Adapter
Display 4 Resolution = Unknown
Display 4 DPI = 96x96
Display 4 Scale = 100% x 100%
Display 5 Scale (legacy) = 100% x 100%
Display 5 Name = \\.\DISPLAY70
Display 5 String = Microsoft Remote Display Adapter
Display 5 Resolution = Unknown
Display 5 DPI = 96x96
Display 5 Scale = 100% x 100%
Display 6 Scale (legacy) = 100% x 100%
Display 6 Name = \\.\DISPLAY71
Display 6 String = Microsoft Remote Display Adapter
Display 6 Resolution = Unknown
Display 6 DPI = 96x96
Display 6 Scale = 100% x 100%
Display 7 Scale (legacy) = 100% x 100%
Display 7 Name = \\.\DISPLAY72
Display 7 String = Microsoft Remote Display Adapter
Display 7 Resolution = Unknown
Display 7 DPI = 96x96
Display 7 Scale = 100% x 100%
Display 8 Scale (legacy) = 100% x 100%
Display 8 Name = \\.\DISPLAY73
Display 8 String = Microsoft Remote Display Adapter
Display 8 Resolution = Unknown
Display 8 DPI = 96x96
Display 8 Scale = 100% x 100%
Display 9 Scale (legacy) = 100% x 100%
Display 9 Name = \\.\DISPLAY74
Display 9 String = Microsoft Remote Display Adapter
Display 9 Resolution = Unknown
Display 9 DPI = 96x96
Display 9 Scale = 100% x 100%
Display 10 Scale (legacy) = 100% x 100%
Display 10 Name = \\.\DISPLAY75
Display 10 String = Microsoft Remote Display Adapter
Display 10 Resolution = Unknown
Display 10 DPI = 96x96
Display 10 Scale = 100% x 100%
Display 11 Scale (legacy) = 100% x 100%
Display 11 Name = \\.\DISPLAY76
Display 11 String = Microsoft Remote Display Adapter
Display 11 Resolution = Unknown
Display 11 DPI = 96x96
Display 11 Scale = 100% x 100%
Display 12 Scale (legacy) = 100% x 100%
Display 12 Name = \\.\DISPLAY77
Display 12 String = Microsoft Remote Display Adapter
Display 12 Resolution = Unknown
Display 12 DPI = 96x96
Display 12 Scale = 100% x 100%
Display 13 Scale (legacy) = 100% x 100%
Display 13 Name = \\.\DISPLAY78
Display 13 String = Microsoft Remote Display Adapter
Display 13 Resolution = Unknown
Display 13 DPI = 96x96
Display 13 Scale = 100% x 100%
Display 14 Scale (legacy) = 100% x 100%
Display 14 Name = \\.\DISPLAY79
Display 14 String = Microsoft Remote Display Adapter
Display 14 Resolution = Unknown
Display 14 DPI = 96x96
Display 14 Scale = 100% x 100%
Display 15 Scale (legacy) = 100% x 100%
Display 15 Name = \\.\DISPLAY80
Display 15 String = Microsoft Remote Display Adapter
Display 15 Resolution = Unknown
Display 15 DPI = 96x96
Display 15 Scale = 100% x 100%
Display 16 Scale (legacy) = 100% x 100%
segoeui.ttf size = 955,804 bytes
tahoma.ttf size = 939,280 bytes
Font Smoothing Enabled = True
Font Smoothing Type = ClearType
Font registry: Segoe UI (TrueType) = 
Font registry: Segoe UI Bold (TrueType) = 
Font registry: Segoe UI Bold Italic (TrueType) = 
Font registry: Segoe UI Italic (TrueType) = 
Font registry: Segoe UI Light (TrueType) = 
Font registry: Segoe UI Semibold (TrueType) = 
Font registry: Segoe UI Symbol (TrueType) = 
Font registry: Tahoma (TrueType) = tahoma.ttf
Font registry: Tahoma Bold (TrueType) = tahomabd.ttf
Font Substitute: Segoe UI = Fira Code
Font Substitute: Tahoma = not found
local_cleaners_dir = C:\Users\margrethe\Desktop\BleachBit-Portable\cleaners
locale_dir = C:\Users\margrethe\Desktop\BleachBit-Portable\share\locale\
options_dir = C:\Users\margrethe\Desktop\BleachBit-Portable
personal_cleaners_dir = C:\Users\margrethe\Desktop\BleachBit-Portable\cleaners
system_cleaners_dir = C:\Users\margrethe\Desktop\BleachBit-Portable\share\cleaners\
os.getenv(APPDATA) = C:\Users\margrethe\AppData\Roaming
os.getenv(cd) = C:\Users\margrethe\Desktop\BleachBit-Portable
os.getenv(LocalAppData) = C:\Users\margrethe\AppData\Local
os.getenv(LocalAppDataLow) = C:\Users\margrethe\AppData\LocalLow
os.getenv(Music) = C:\Users\margrethe\Music
os.getenv(USERPROFILE) = C:\Users\margrethe
os.getenv(ProgramFiles) = C:\Program Files (x86)
os.getenv(ProgramW6432) = C:\Program Files
os.getenv(TMP) = C:\Users\MARGRE~1\AppData\Local\Temp
os.path.expanduser(~") = C:\Users\margrethe
platform.uname().version = 10.0.19045
sys.argv = ['C:\\Users\\margrethe\\Desktop\\BleachBit-Portable\\bleachbit.exe']
sys.executable = C:\Users\margrethe\Desktop\BleachBit-Portable\bleachbit.exe
sys.version = 3.11.10 (main, Feb 16 2025, 04:46:39) [MSC v.1942 32 bit (Intel)]
IsUserAnAdmin() = True
__file__ = C:\Users\margrethe\Desktop\BleachBit-Portable\library.zip\bleachbit\SystemInformation.pyc
```

**Comment by Coccocoahelper** [comment]
> > I have set the system font to Fira Code using Winaero Tweaker, changing to the Nerd Font variant of Fira Code (while causing other issues), and now back to Fira Code again. Seems to have just started working again...
> 
> [@tordenflesk](https://github.com/tordenflesk) Thank you. Now I found one way to reproduce this, which was helpful for testing. Specifically, I ran `choco install firacodeng` to get FiraCode NF version 6.2.0. Then I used Winaero Tweaker to set it as the system font, which substitutes it for Segoe UI.
> 
> Here's what I found in testing.
> 
> Setting the Windows system font to Times New Roman doesn't trigger the problem in BleachBit, so it's not font substitution in general. Setting BleachBit to FiraCode NF doesn't trigger the bug, so it's the specific substitution. The issue may happen with substituting some other fonts, but it's not all fonts.
> 
> The bug is related to the font stack involving GTK, pango (used for displaying text), and Windows, but it's hard to pinpoint and fix. It happens when the stack is compiled with vcpkg, but not with msys2---though I couldn't compare the same versions of all the packages in the stack.
> 
> The bug seems _not_ related to:
> 
> * Windows Region Settings: Current system locale/Use Unicode UTF-8 for worldwide language support
> * display language in BleachBit
> * Windows vs Adwaita theme in BleachBit
> * dark/light theme in BleachBit
> * gtk.css (can be used to pick a different font, which helps)
> * deleting the `%localappdata%\fontconfig` directory
> 
> [@Coccocoahelper](https://github.com/Coccocoahelper)
> 
> **Have you done any of these?**
> 
> * Used Winaero Tweaker
> * Changed your Windows system font another way like editing the registry
> * Installed the font Fira Code NF
> * Set up any font substitutions, specially for Segoe UI (default system font on Windows)
> 
> Please try the new build [5.0.0.2974-badtext](https://ci.bleachbit.org/?prefix=dl/5.0.0.2974-badtext/). The bug is not fixed, by default, it will not use Segoe UI. You can pick other fonts using the headerbar (main window) or in the preferences dialog.
> 
> On the toolbar is a button to show system information, and today I enhanced it to record more info that may help. **Please copy that information to the clipboard, and paste it here.** You may delete the line with `local_options_dir` and all lines below.

I might have used Winaero Tweaker, but nothing else, if I recall. Any system fix available?

**Comment by az0** [comment]
@Coccocoahelper :
If you still have Winaero Tweaker, please check the setting for System
Font. Is it on default or custom font? If it's default, I am not sure
what's causing the issue for you.

If the system font is not default, you can change it to default.
Otherwise, an option is to change the font in BleachBit using the new
build 2974, which defaults to a font that probably works. Another
option is downgrading to BleachBit 4.6.2.

**Comment by Coccocoahelper** [comment]
> [@Coccocoahelper](https://github.com/Coccocoahelper) :
> If you still have Winaero Tweaker, please check the setting for System
> Font. Is it on default or custom font? If it's default, I am not sure
> what's causing the issue for you.
> 
> If the system font is not default, you can change it to default.
> Otherwise, an option is to change the font in BleachBit using the new
> build 2974, which defaults to a font that probably works. Another
> option is downgrading to BleachBit 4.6.2.

The dev build did work, tysm.

**Comment by Coccocoahelper** [comment]
> [@Coccocoahelper](https://github.com/Coccocoahelper) :
> If you still have Winaero Tweaker, please check the setting for System
> Font. Is it on default or custom font? If it's default, I am not sure
> what's causing the issue for you.
> 
> If the system font is not default, you can change it to default.
> Otherwise, an option is to change the font in BleachBit using the new
> build 2974, which defaults to a font that probably works. Another
> option is downgrading to BleachBit 4.6.2.

If I did have Winaero (might have used it a long time ago, don't fully recall it), I don't have it, right now.

**Comment by az0** [comment]
Scott is actively working on changes that may fix the root problem.

Meanwhile, I am considering adding a step to the application startup that shows this dialog window. It renders text using the default font (which sometimes renders badly) and an alternative font (which always should be okay).
<img width="764" height="252" alt="Image" src="https://github.com/user-attachments/assets/22f4ddd7-908e-4771-8f73-315fc057831b" />
If the user reports a problem, it changes the PANGOCAIRO_BACKEND and/or default font, restarts the application, and asks again.

When it finds a good setting, it remembers it, and won't keep showing the dialog.

Thoughts?

**Comment by Coccocoahelper** [comment]
> Scott is actively working on changes that may fix the root problem.
> 
> Meanwhile, I am considering adding a step to the application startup that shows this dialog window. It renders text using the default font (which sometimes renders badly) and an alternative font (which always should be okay). <img alt="Image" width="764" height="252" src="https://private-user-images.githubusercontent.com/933680/518433292-22f4ddd7-908e-4771-8f73-315fc057831b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwNTczOTMsIm5iZiI6MTc2NDA1NzA5MywicGF0aCI6Ii85MzM2ODAvNTE4NDMzMjkyLTIyZjRkZGQ3LTkwOGUtNDc3MS04ZjczLTMxNWZjMDU3ODMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNVQwNzUxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzM1YjY4ZGNjNGQyMWE1YzUzZDEwMDNiNThiMTZlOGZhM2MxYmUxZmJjY2E1ZmI0Yjk2MjA3ODBkOWYwODIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mXcfkQB0uJRjGKxyz6f9Ee-xqLjfgaZ1b_5Mm2JM-Js"> If the user reports a problem, it changes the PANGOCAIRO_BACKEND and/or default font, restarts the application, and asks again.
> 
> When it finds a good setting, it remembers it, and won't keep showing the dialog.
> 
> Thoughts?

That seems like a great idea! If I could afford to donate, I definitely would; you are all very competent developers.
