### ISSUE TITLE
Some files are not deleted...

### ISSUE THREAD

**Issue by PiliJ** [bleachbit/bleachbit#536]
I use the program with "winapp2.ini" and I checked in particular VirtualBox.
Noting that log-files are not deleted, I added their folders in the personalised preferences of Bleachbit... in vain, the log-files stays in place. Bug ?
Thank you.

**Comment by az0** [comment]
Which version of BleachBit?

In BleachBit did you check the box called **System - Custom**?

When you click Clean or Preview in BleachBit, does it show the VirtualBox log? Or does it show an error?

**Comment by PiliJ** [comment]
Hi Andrew,

You'll find in attach the asked info...

Best regards.
 
 
 
-----Original Message-----

**Comment by PiliJ** [comment]
I forget to answer your question :
"When you click Clean or Preview in BleachBit, does it show the VirtualBox log? Or does it show an error?"
No to the 2 questions.
 
 
 
-----Original Message-----

**Comment by PiliJ** [comment]
Here are the errors in BleachBit Andrew...

...
 
 
 
-----Original Message-----

**Comment by Tobias-B-Besemer** [comment]
@PiliJ, there are now errors! Did you forgot to attach them ???

**Comment by az0** [comment]
To attach an image, drop it onto the typing area in GitHub. It might not work if you send it by email.

**Comment by PiliJ** [comment]
![Image 001](https://user-images.githubusercontent.com/33757855/56431731-2202c200-62cb-11e9-8978-dc2ad314caee.png)

**Comment by PiliJ** [comment]
![Image 002](https://user-images.githubusercontent.com/33757855/56431775-4eb6d980-62cb-11e9-98d4-c805c4b62611.png)

**Comment by Tobias-B-Besemer** [comment]
But this errors seems to come from MS Office Word... Had you Word open while you ran the cleanup?

**Comment by PiliJ** [comment]
No.
I just redo a cleaning and it's always the same thing ...(see new snapshot).
Note that during the cleaning, an error is indicated for the optimatization of places-SQLite of Waterfox, but that it does not appear/more when the operation is completed.
In fact, these mistakes do not bother me too much. I am more bothered by the problem initially reported : log-files are not deleted although indicated in the personalized settings.
THank you.
![Image 003](https://user-images.githubusercontent.com/33757855/56436638-d527e700-62dc-11e9-834f-d0f5722384bc.png)

**Comment by PiliJ** [comment]
Error on my part ... sorry : the error of Waterfox is well there !
I thought that all the mistakes were brought back above the end result, but this is not the case :+1: 
![Image 004](https://user-images.githubusercontent.com/33757855/56436997-24bae280-62de-11e9-9be5-eb9427273a97.png)

**Comment by Tobias-B-Besemer** [comment]
OK, in your first screenshot I can read (in red) `ms_office` and then `word`...
BB can not really clean files that are locked by other programs!
So the question is, if you have open Word in the background and Waterfox?
Can this programs be minimized into system tray?
Are they maybe there open?
Can you check your task manager, if the programs are open?

And now back to your initial problem ...
> I checked in particular VirtualBox. Noting that log-files are not deleted

Can you un-check all other cleaners expecting the VirtualBox-Cleaner, run a new cleanup, make a new screenshot and load them here up?
It would help to isolate the problem and only see the output of the VirtualBox-Cleaner...

And then: Which VirtualBox-Log doesn't get deleted?
Can you make a screenshot from the file in your Explorer showing the filename and the path to it and then load the screenshot here up again?

**Comment by PiliJ** [comment]
OK here is the desktop... no Word or Waterfox open :
![Image 001](https://user-images.githubusercontent.com/33757855/56439177-803c9e80-62e5-11e9-9b42-0aeda67c18bb.png)
Result of BleachBit :+1: 
![Image 002](https://user-images.githubusercontent.com/33757855/56439209-a06c5d80-62e5-11e9-8745-2d030035c8a7.png)
and...
![Image 003](https://user-images.githubusercontent.com/33757855/56439213-a8c49880-62e5-11e9-930c-2f255c50d5e9.png)
Meanwhile, i deleted menually the log-files of VirtualBox, but here they are in the settings :+1: 
![Image 002](https://user-images.githubusercontent.com/33757855/56439268-d578b000-62e5-11e9-8a7a-afb463b54240.png)
Thanks.

**Comment by Tobias-B-Besemer** [comment]
Is it possible that you changed the location where your VMs get saved ???
On my system it is/was under `C:\Users\Administrator\VirtualBox VMs`.
If you change the path where you save files, nor BleachBit, nor WinApp2.ini can find it...

**Comment by Tobias-B-Besemer** [comment]
Also: My Logs are under `C:\Users\Administrator\.VirtualBox`...

**Comment by Tobias-B-Besemer** [comment]
K, have Logs-Folders under the VMs, too.

**Comment by Tobias-B-Besemer** [comment]
@PiliJ, did you what Andrew wrote:
> In BleachBit did you check the box called **System - Custom**?

Means: By the Cleaner "System" you need to check the option "Custom" that the files specified in the Preferences of BB get deleted.

**Comment by PiliJ** [comment]
I did not change anything at the installation of VirtualBox. Actual version is 6.0.4 r128413 (Qt5.6.2) and i have updated it regularly since version 5.1.10-112026 by crushing the old version.
I'm under Win 8.1.
I didn't quite understand what Andrew meant, but I found it and ticked it now... now also there are errors for the log- files of VBox !
![Image 004](https://user-images.githubusercontent.com/33757855/56444382-c4856a00-62f8-11e9-9da5-97bbbf4a1a74.png)

Problem is solved !
THank you very much.

**Comment by PiliJ** [comment]
It goes without saying that I remain at your disposal for the other errors.

**Comment by PiliJ** [comment]
Hello again,
I don't know why, but all asd-files giving an error were "read-only".
I thus changed that and the only remaining error is the one relating to places.sqlite of Waterfox ...
Best regards.

**Comment by Tobias-B-Besemer** [comment]
Hi!
Now more then a half year passed by, and so it's IMHO really time to have a lock at this ussue, again! ;)
A lot of things changed in this time, so IMHO we should first verify, that the issue still exist and if his appearance have changed!
In the meantime BB 3 got released, so you should make sure, that you have it installed and don't used BB2, anymore!
Also a lot hace changed on the rules file WinApp2.ini, but BB3 will download the newest version automatically...
After the updates of BB & WinApp2.ini you should make new tests and report how it looks now.
Maybe you will still get errors, but there is now a light at the end visible... ;)
...then in issue https://github.com/bleachbit/bleachbit/issues/337 got looked files that can't be deleted reported, too, and @az0 will hopefully work on a solution, soon.
If this all will not solve your issues, I will after it have a look on the cleaning rules and write/improve cleaner files for you! ;)
You must know to it, that WinApp2.ini, the file that privides the cleaning rules you work ATM come from a other project and this project (ours) can't have always the influence on the other project (WinApp2.ini) like we would prefer... but we are able to write our own, more improved cleaning files and I will then take the time to do this to resolve your issue! ;)
But first, as I have written above, you should update, test and report all, again! Sorry for that !!!
Greets, Tobias.

**Comment by PiliJ** [comment]
Hi Tobias,
1) The last version of the program was already installed and i updated the WinApp2.ini-file.
2) I found that the "sqlite" files of Waterfox are no longer optimized.... normal?
3) For VirtualBox, the files with the log extension were previously in a folder called Log as well. This is no longer the case, they are in different folders with a letter (following which? an update of Windows?):
![Image 002](https://user-images.githubusercontent.com/33757855/70071291-642c0a00-15f5-11ea-81c3-ac8bd44dd7b9.jpg)
![Image 003](https://user-images.githubusercontent.com/33757855/70071292-64c4a080-15f5-11ea-9e19-324757beb1c0.jpg)
This is not only the case with VB, I have the same thing under C:\Users\XX\AppData\Roaming\FreeFileSync for example :
![Image 003](https://user-images.githubusercontent.com/33757855/70071339-84f45f80-15f5-11ea-8159-c146ae67840e.jpg)
![Image 002](https://user-images.githubusercontent.com/33757855/70071340-84f45f80-15f5-11ea-8fd7-fe97ebfce31c.jpg)
Anyway, whether I indicate the folder(s) or file(s)  they are now deleted correctly !

**Comment by Tobias-B-Besemer** [comment]
> Hi Tobias,

Hi! :)

>     2. I found that the "sqlite" files of Waterfox are no longer optimized.... normal?

No, normally not! It's called "Vacuum" in US English. Goes normally real fast! I had ATM a look at the cleaner and the code for it is still included! Why do you think the SQLite files get no more optimized (on your system) ???

>     3. For VirtualBox, the files with the log extension were previously in a folder called Log as well. This is no longer the case, they are in different folders with a letter (following which? an update of Windows?):

Pretty sure it's not a update of Windows!
OK, it can be a update from VB, haven't my install not updated in the last year, but looks a bit strange anyway...
Do you lately have something changed (a setting) in VB ??? Do you work with snapshots of your VMs ??? Then maybe it's normal, but I never saw this before...
More strange is, that you have it in your FreeFileSync folder, too! What us in all those folders with just one letter ??? Do all include VB Logs even those in the system folder of FreeFileSync ???
The folders seems to be all created lately this year... Do you have anything changed in this time ??? Since shen do you use FreeFileSync and since when Google Drive ???
Also it would be possible that something with your file system goes terrible wrong!
Can you open the command prompt of Windows with entering CMD as the program you want to start in the search field of you start menu (hope it works still the same on Win10, then unfortunately I'm stlll on Win7 :-/) and then enter the following command in the prompt:
chkdsk C: /f
This will start a "check disk" on your next computer start/reboot, will check the file system and because of "/f" will fix problems, too, if any found.

>        Anyway, whether I indicate the folder(s) or file(s)  they are now deleted correctly !

You must select on the left side, as an option of the system cleaner, that custom rules should get executed, do you still remember that ???

>        P.S. : someting goes wrong with the snapshots !

About which snapshots do you talk now? Because snapshot is meanwhile a word used for many things by many vendors.
And can you something more specify "something gies wrong"?

Greets, Tobias.

**Comment by PiliJ** [comment]
1) "Why do you think the SQLite files get no more optimized"
Before version 3, the optimization/vacuum was always visible on the cleaning report (see my snapshots above). I don't see anything like that anymore.

2) No change in VB, just the regular update. On the other hand, I do a minimum of snapshots.
There are the same log files in all the folders with a letter but at different dates(VBox.log,VBox.log1,VBox.log2 and VBoxHardening.log).
In those of FreeFileSync there all kinds of log related to the operation (errors, warnings, etc.).
The one of Google Drive is empty (i don't use it and is not on the PC).

3) I did a chkdsk and a sfc /scannow without error at the first sight.

4) VB is checked on the left, but if if I don't specify the files/folders, nothing is deleted.

5) I was talking about the snpashots I added in my last post by copy/paste and which are upside down.

Thank you Tobias!
