### ISSUE TITLE
Problems wiping memory;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [bleachbit/bleachbit#575]
Very rarely it will work but most of the time I get this...

> Error: system.memory: Function: Memory
Traceback (most recent call last):
  File "/home/****/bleachbit/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/****/bleachbit/bleachbit/Command.py", line 147, in execute
    for func_ret in self.func():
  File "/home/****/bleachbit/bleachbit/Memory.py", line 307, in wipe_memory
    wipe_swap_linux(devices, proc_swaps)
  File "/home/****/bleachbit/bleachbit/Memory.py", line 277, in wipe_swap_linux
    logger.info(_("Wiping the swap device %s.") % device)
UnboundLocalError: local variable '_' referenced before assignment
Traceback (most recent call last):
  File "/home/****/bleachbit/bleachbit/Worker.py", line 299, in run
    self.ui.worker_done(self, self.really_delete)
  File "/home/****/bleachbit/bleachbit/GUI.py", line 687, in worker_done
    notify.set_hint("desktop-entry", "bleachbit")
TypeError: argument value: Expected GLib.Variant, but got str

**Note: If I select only memory it works?**

**Comment by az0** [comment]
Thanks for the report. I'll check into it

**Comment by Ub3rZ4cH** [comment]
This time I tried to check just memory, and it gave me the same error, so it looks like it doesn't work all the time individually, but it worked when I selected everything except for this if this means anything...

`The child memory-wiping process returned code 9.`

**Comment by az0** [comment]
Today I pushed the fix to Git. It looks like you are using a version from Git, so please update it and try again.

**Comment by Ub3rZ4cH** [comment]
Thanks

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

**Comment by Ub3rZ4cH** [comment]
> You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

Yeah I can confirm in 2.3, the memory wiping is working as intended now :)

**Comment by allanromanreyes** [comment]
Still getting Error: system.memory: Function: Memory eroor when running Administrator cleaning on Raspberry Pi 4B 8GB:

error block:
Error: system.memory: Function: Memory
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 145, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Memory.py", line 315, in wipe_memory
    fill_memory_linux()
  File "/usr/share/bleachbit/Memory.py", line 143, in fill_memory_linux
    buf = '\x00' * allocbytes
OverflowError: cannot fit 'int' into an index-sized integer
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.[Errno 13] Permission denied: '/root/.cache': Function: Overwrite free disk space /root/.cache
Disk space recovered: 13MiB
Files deleted: 542
Special operations: 6
Errors: 2

Diagnostics:
BleachBit version 4.1.1
Git revision 940c1c39
GTK version 3.24.5
GTK theme = PiXflat
GTK icon theme = PiXflat
GTK prefer dark theme = True
SQLite version 3.27.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /root/.config/bleachbit
personal_cleaners_dir = /root/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = root
os.getenv('USER') = root
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /root
platform.linux_distribution() = ('debian', '10.7', '')
platform.platform = Linux-5.4.79-v7l+-armv7l-with-debian-10.7
platform.version = #1373 SMP Mon Nov 23 13:27:40 GMT 2020
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by az0** [comment]
@allanromanreyes 
> Still getting Error: system.memory: Function: Memory error when running Administrator cleaning on Raspberry Pi 4B 8GB:

Your traceback `OverflowError: cannot fit 'int' into an index-sized integer` indicates there is a different kind of problem here. Please file a new issue ticket.
