### ISSUE TITLE
Error when checking for updates on Ubuntu 20.04

### ISSUE THREAD

**Issue by mcl21014** [bleachbit/bleachbit#819]
BB Version: 3.9.0 beta
OS Version: Linux, Ubuntu 20.04 dev branch amd64

Good news is that it runs on 20.04. Bad news is the output before I do anything with the application is there's red text in the output window reading:
"Error when checking for updates: 
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 1160, in check_online_updates
    updates = Update.check_updates(options.get('check_beta'),
  File "/usr/share/bleachbit/Update.py", line 155, in check_updates
    opener.addheaders = [('User-Agent', user_agent())]
  File "/usr/share/bleachbit/Update.py", line 87, in user_agent
    dist = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'
"
Might be related, but check for updates is toggled on. Not the beta switch, though. Only happens when the "Check for updates via the internet" option is on. Can reproduce on my system.

**Comment by az0** [comment]
Good report. Thanks

**Comment by mkhon** [comment]
Fixed in #826

**Comment by az0** [comment]
@mcl21014 

Are you able to test Max's fix by [running from source](https://docs.bleachbit.org/dev/running-from-source-code.html)?

The commands are

````
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python3 bleachbit.py
````

**Comment by mcl21014** [comment]
@az0 I tested it after cloning and it's no longer an issue.

**Comment by az0** [comment]
> @az0 I tested it after cloning and it's no longer an issue.

Thank you for testing. Now, I will close the ticket

**Comment by NeillRu** [comment]
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python3 bleachbit.py

I confirm that this works on Linux Mint 20 but the menu item still points at the old package and hence the errors remain. Need best practise to ensure the correct package is installed.Simply copying the new file does not do it program starts then aborts...

**Comment by az0** [comment]
> I confirm that this works on Linux Mint 20 but the menu item still points at the old package and hence the errors remain. Need best practise to ensure the correct package is installed.Simply copying the new file does not do it program starts then aborts...

Yes, this doesn't update the system copy of BleachBit, and the shortcuts (application launcher) will point to the system copy.

As a temporary workaround, navigate to the Git copy and updated files like this

`sudo cp bleachbit/{Update,Diagnostic,_init_._platform}.py  /usr/share/bleachbit/`

A cleaner solution is to wait until the beta or final release with the fix.
